import React from "react";
import "./globals.css";
import { Metadata } from "next";
import UserAuthHandler from "@/components/UserAuthHandler";

export const metadata: Metadata = {
  title: "Afo Cyber Sec",
  icons: [
    {
      url: "/logo-test.png",
    },
  ],
  // description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <UserAuthHandler>{children}</UserAuthHandler>
      </body>
    </html>
  );
}
